import type { SupabaseClient } from "@supabase/supabase-js"

import type { Database } from "@/lib/supabase/database.types"
import { AU_STATES } from "@/lib/validations/postcode"
import {
  enumParam,
  escapeLike,
  positiveIntParam,
  textParam,
  type SearchParams,
} from "@/lib/queries/search-params"

export const POSTCODE_ZONES_PAGE_SIZE = 25

// Read-only. This table is generated by scripts/reference/export-carrier-zones.mjs
// and has no write policy (migration 20260812100000) -- correcting a zone means
// re-exporting, not editing a row here. The page exists so the mapping the
// engine used can be looked up when a quote comes out wrong.
export type PostcodeZoneRow = {
  id: number
  carrier_id: number
  zone: string
  surcharge: number
  postcode: { postcode: string; locality: string; state: string | null } | null
}

export type PostcodeZoneFilters = {
  postcode: string | null
  locality: string | null
  state: string | null
  carrierId: number | null
  zone: string | null
  page: number
}

export function parsePostcodeZoneFilters(
  params: SearchParams
): PostcodeZoneFilters {
  return {
    postcode: textParam(params, "postcode"),
    locality: textParam(params, "locality"),
    state: enumParam(params, "state", AU_STATES),
    carrierId: positiveIntParam(params, "carrier"),
    zone: textParam(params, "zone"),
    page: positiveIntParam(params, "page") ?? 1,
  }
}

export type PostcodeZoneListResult = {
  rows: PostcodeZoneRow[]
  count: number
  error: string | null
}

export async function fetchPostcodeZoneList(
  supabase: SupabaseClient<Database>,
  filters: PostcodeZoneFilters
): Promise<PostcodeZoneListResult> {
  // !inner, so a filter on the postcodes side restricts the zone rows rather
  // than merely nulling the embedded object.
  let query = supabase
    .from("postcode_carrier_zones")
    .select(
      "id, carrier_id, zone, surcharge, postcode:postcodes!inner(postcode, locality, state)",
      { count: "exact" }
    )
    // Ordering by an embedded column needs referencedTable; it takes the
    // relation's real name, not the `postcode:` alias used in the select.
    .order("postcode", { referencedTable: "postcodes", ascending: true })
    .order("locality", { referencedTable: "postcodes", ascending: true })
    .order("carrier_id", { ascending: true })

  if (filters.postcode) {
    query = query.like("postcodes.postcode", `${escapeLike(filters.postcode)}%`)
  }
  if (filters.locality) {
    query = query.ilike("postcodes.locality", `%${escapeLike(filters.locality)}%`)
  }
  if (filters.state) {
    query = query.eq("postcodes.state", filters.state)
  }
  if (filters.carrierId) {
    query = query.eq("carrier_id", filters.carrierId)
  }
  if (filters.zone) {
    query = query.eq("zone", filters.zone)
  }

  const from = (filters.page - 1) * POSTCODE_ZONES_PAGE_SIZE
  const to = from + POSTCODE_ZONES_PAGE_SIZE - 1

  const { data, count, error } = await query.range(from, to)
  if (error) return { rows: [], count: 0, error: error.message }

  return {
    rows: (data ?? []) as unknown as PostcodeZoneRow[],
    count: count ?? 0,
    error: null,
  }
}

// The zone filter's options. Distinct values across both carriers -- eight in
// practice, small enough to render as a select rather than a text box.
export async function fetchZoneOptions(
  supabase: SupabaseClient<Database>
): Promise<string[]> {
  const { data } = await supabase.from("carrier_zones").select("zone")
  return [...new Set((data ?? []).map((row) => row.zone))].sort()
}
