-- Give the shipping reference tables a write surface, so /settings/shipping can
-- maintain them instead of every rate change needing a migration.
--
-- 20260810100000 created all six read-only on purpose. That was right while the
-- only consumer was the quote engine (which runs under the service role and
-- bypasses RLS anyway); it stops being right the moment a human has to adjust a
-- negotiated rate.
--
-- Two things this migration is careful about, both of them consequences of
-- CLAUDE.md rule 22 -- RLS is the gate, GRANT is decoration:
--
--   * Opening a table means adding a POLICY. The GRANT lines that already sit
--     in 20260810100000 never gated anything.
--   * Closing a single COLUMN is the one case where grants do matter, and only
--     in the REVOKE-then-GRANT order: column grants are additive and cannot
--     shrink a table-level privilege that Supabase's default ACL already gave
--     away.
--
-- postcode_carrier_zones is deliberately NOT opened. Its page is a read-only
-- browser: 33,424 rows generated by scripts/reference/export-carrier-zones.mjs,
-- re-exported rather than hand-edited.

BEGIN;

-- ── carriers ────────────────────────────────────────────────────────────────
--
-- INSERT and UPDATE, no DELETE. Deleting a carrier cascades into
-- carrier_services -> carrier_zone_rates, carrier_dispatch_options and its
-- ~16,500 postcode_carrier_zones rows, and none of that is recoverable from the
-- UI. Retiring one is what is_active is for.

CREATE POLICY "authenticated_insert" ON public.carriers
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated_update" ON public.carriers
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- `code` is a code-coupled key, not a label: CARRIER_CAPABILITIES in
-- src/lib/shipping/carrier-capabilities.ts is keyed by it, and so is
-- quoteStrategyFor's `=== 'aramex'` test. Editing it detaches a carrier from
-- its own weight and dimension limits without raising anything -- the quotes
-- just come out different. Settable once at INSERT, immutable afterwards.
REVOKE UPDATE ON public.carriers FROM authenticated;
GRANT UPDATE (name, is_active) ON public.carriers TO authenticated;

-- ── carrier_services ────────────────────────────────────────────────────────

CREATE POLICY "authenticated_write" ON public.carrier_services
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── carrier_zone_rates ──────────────────────────────────────────────────────

CREATE POLICY "authenticated_write" ON public.carrier_zone_rates
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── carrier_dispatch_options ────────────────────────────────────────────────

CREATE POLICY "authenticated_write" ON public.carrier_dispatch_options
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── flat_rate_package_specs ─────────────────────────────────────────────────

CREATE POLICY "authenticated_write" ON public.flat_rate_package_specs
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ── shipping_settings ───────────────────────────────────────────────────────
--
-- UPDATE only, like pricing_settings: one row, seeded by migration, guarded by
-- CHECK (id = 1). An INSERT policy could only ever produce a constraint error,
-- and a DELETE policy would let the UI remove the row the engine reads.

CREATE POLICY "authenticated_update" ON public.shipping_settings
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- ── carrier_zones ───────────────────────────────────────────────────────────
--
-- The zone axis of the rate card matrix. Columns come from what the zone table
-- actually holds for a carrier, unioned with whatever its rate card already
-- prices -- a zone with a rate but no postcodes still has to be visible, or the
-- page would hide a row the engine can still hit.
--
-- A view rather than a DISTINCT in the query layer: 32,912 rows is a full scan
-- per page load otherwise. security_invoker = true, or it would run as its
-- owner and hand out rows RLS is meant to gate.
CREATE VIEW public.carrier_zones
WITH (security_invoker = true) AS
SELECT carrier_id, zone
FROM public.postcode_carrier_zones
UNION
SELECT s.carrier_id, r.zone
FROM public.carrier_zone_rates r
JOIN public.carrier_services s ON s.id = r.service_id;

COMMENT ON VIEW public.carrier_zones IS
  'Distinct zones per carrier, from the postcode table and the rate card together. Column axis for /settings/shipping/rate-cards.';

COMMIT;
