BEGIN;

-- Currency enum used by public.products.currency.
-- See docs/products-domain-migration.md section 3/4 for the migration decisions this schema implements.
CREATE TYPE public.currency_code AS ENUM ('USD', 'AUD', 'CNY');

-- 1. origins (source: go2_origins)
CREATE TABLE public.origins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  abbr text
);

ALTER TABLE public.origins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.origins
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.origins TO authenticated;

-- 2. brands (source: go2brands)
CREATE TABLE public.brands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  abbr text
);

ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.brands
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.brands TO authenticated;

-- 3. suppliers (source: go2_suppliers)
CREATE TABLE public.suppliers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name text,
  contact_person text,
  email text,
  phone text,
  comments text
);

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.suppliers
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.suppliers TO authenticated;

-- 4. products (source: go2_products)
CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL UNIQUE,
  model text,
  upc text,
  brand_id bigint REFERENCES public.brands (id),
  name text,
  image_url text,
  origin_id bigint NOT NULL REFERENCES public.origins (id),
  supplier_id bigint REFERENCES public.suppliers (id),
  currency public.currency_code,
  purchase_price numeric,
  is_gst boolean NOT NULL,
  weight numeric(10, 3) NOT NULL,
  length numeric(10, 2) NOT NULL,
  width numeric(10, 2) NOT NULL,
  height numeric(10, 2) NOT NULL,
  retail_price numeric,
  is_active boolean NOT NULL,
  comment text,
  is_kit boolean NOT NULL,
  ebay_title text,
  description text,
  created_at timestamptz,
  updated_at timestamptz
);

CREATE INDEX products_brand_id_idx ON public.products (brand_id);
CREATE INDEX products_origin_id_idx ON public.products (origin_id);
CREATE INDEX products_supplier_id_idx ON public.products (supplier_id);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.products
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;

COMMIT;
