BEGIN;

-- Cost-banded markup multipliers used to derive a suggested retail price from
-- landed unit cost. See docs/product-pricing-view.md section 4 for the reasoning
-- behind banded (rather than flat) markup.
--
-- Stored as rows rather than hardcoded in the view so the bands can be
-- recalibrated from the Settings page without a migration — they are expected to
-- change once real markup data is back-calculated from existing retail prices.
CREATE TABLE public.pricing_markup_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Band is [min_cost, max_cost) over the landed unit cost in AUD ex-GST.
  min_cost numeric(12, 2) NOT NULL,
  -- NULL means "no upper bound" — the top band.
  max_cost numeric(12, 2),
  multiplier numeric(6, 3) NOT NULL,
  CONSTRAINT pricing_markup_tiers_min_cost_non_negative CHECK (min_cost >= 0),
  CONSTRAINT pricing_markup_tiers_range_ordered CHECK (max_cost IS NULL OR max_cost > min_cost),
  -- A multiplier below 1 would price goods under cost; that is never a tier
  -- setting, it is a data-entry error.
  CONSTRAINT pricing_markup_tiers_multiplier_above_one CHECK (multiplier >= 1),
  CONSTRAINT pricing_markup_tiers_unique_min_cost UNIQUE (min_cost)
);

-- The view looks up a tier by scanning for the band containing a given cost.
CREATE INDEX pricing_markup_tiers_min_cost_idx ON public.pricing_markup_tiers (min_cost);

-- Starting bands: low-cost items need a higher multiplier because per-order
-- fulfilment overhead does not scale down with value, while high-value items
-- face cross-retailer price comparison and must converge.
INSERT INTO public.pricing_markup_tiers (min_cost, max_cost, multiplier) VALUES
  (0,   2,    5.0),
  (2,   5,    4.0),
  (5,   15,   3.2),
  (15,  40,   2.6),
  (40,  100,  2.2),
  (100, NULL, 1.9);

ALTER TABLE public.pricing_markup_tiers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.pricing_markup_tiers
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.pricing_markup_tiers TO authenticated;

COMMIT;
