BEGIN;

-- Reference tables for the shipping quote engine, ported from xpros.
-- See docs/shipping-quote-engine.md sections 2.2 - 2.8.
--
-- What this domain does: given an order's packed weight and dimensions and the
-- customer's postcode, price it against every carrier we can actually use and
-- pick the cheapest. Six tables:
--
--   carriers                 who we can ship with
--   carrier_services         weight tiers per carrier and service level
--   carrier_zone_rates       the rate card: price per (tier, zone)
--   carrier_dispatch_options which shipping_method values take part in quoting
--   flat_rate_package_specs  Australia Post satchel/box sizes
--   shipping_settings        the handful of global constants
--
-- postcode_carrier_zones (postcode -> zone) is large and generated, so it lives
-- in its own migration, 20260810130000.
--
-- Three of xpros' six carriers are deliberately absent (decisions 1, 2 and the
-- Z6/Z9 note in section 1): the retired eParcel Z6 account, Direct Freight, and
-- the per-state eParcel origins. That last one is why no table here carries an
-- origin_warehouse_id -- go2office ships from one place.

-- ── carriers ────────────────────────────────────────────────────────────────

CREATE TABLE public.carriers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- This is a code identifier, not a label: CARRIER_CAPABILITIES in
  -- src/lib/shipping keys off it, so editing a value here silently detaches a
  -- carrier from its own weight and dimension limits. Hence UNIQUE + a
  -- lowercase CHECK, the same "lock down what must not drift" treatment
  -- countries.country_code gets. Rename in `name`, never here.
  code text NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT carriers_code_unique UNIQUE (code),
  CONSTRAINT carriers_code_lower CHECK (code = lower(code))
);

CREATE TRIGGER carriers_set_updated_at
  BEFORE UPDATE ON public.carriers
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

-- ── carrier_services ────────────────────────────────────────────────────────

CREATE TABLE public.carrier_services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  carrier_id bigint NOT NULL REFERENCES public.carriers (id) ON DELETE CASCADE,
  service_type text NOT NULL,
  size_label text NOT NULL,
  -- NULL marks the per-kg overflow tier, which applies above every fixed tier.
  -- At most one per (carrier, service_type) -- the rate lookup sorts fixed
  -- tiers by weight and falls through to this one, so a second would be
  -- unreachable.
  max_weight numeric(10, 3),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT carrier_services_unique UNIQUE (carrier_id, service_type, size_label),
  CONSTRAINT carrier_services_type_lower CHECK (service_type = lower(service_type))
);

CREATE TRIGGER carrier_services_set_updated_at
  BEFORE UPDATE ON public.carrier_services
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

-- ── carrier_zone_rates ──────────────────────────────────────────────────────

CREATE TABLE public.carrier_zone_rates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id bigint NOT NULL REFERENCES public.carrier_services (id) ON DELETE CASCADE,
  zone text NOT NULL,
  -- Fixed tiers price off `rate`; the per-kg tier prices off base_rate +
  -- per_kg_rate, floored at min_charge.
  rate numeric(10, 2),
  base_rate numeric(10, 2),
  per_kg_rate numeric(10, 2),
  min_charge numeric(10, 2),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT carrier_zone_rates_unique UNIQUE (service_id, zone),
  -- Not in xpros. A row with neither pricing method filled in returns $0, and
  -- $0 wins the cheapest-option comparison outright -- so a typo here would not
  -- raise anything, it would mark an order as free to ship.
  CONSTRAINT carrier_zone_rates_has_pricing CHECK (
    rate IS NOT NULL OR (base_rate IS NOT NULL AND per_kg_rate IS NOT NULL)
  )
);

CREATE TRIGGER carrier_zone_rates_set_updated_at
  BEFORE UPDATE ON public.carrier_zone_rates
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

-- ── carrier_dispatch_options ────────────────────────────────────────────────

CREATE TABLE public.carrier_dispatch_options (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipping_method public.shipping_method NOT NULL,
  carrier_id bigint NOT NULL REFERENCES public.carriers (id) ON DELETE CASCADE,
  billing_weight_mode text NOT NULL DEFAULT 'chargeable',
  -- Joins to carrier_services.service_type.
  --
  -- xpros stores 'Standard'/'Express' here but 'standard'/'express' there, and
  -- papers over the mismatch with a .toLowerCase() at each of the two call
  -- sites that survived. The third caller, calculate-rate.ts, does not
  -- lowercase and would find no tiers at all -- it is dead code, which is the
  -- only reason nobody noticed. Storing one case on both sides is what makes
  -- that class of bug impossible rather than merely unobserved.
  service_type text,
  -- Non-NULL short-circuits everything: no zone lookup, no rate card.
  fixed_price_aud numeric(10, 2),
  max_order_total_aud numeric(10, 2),
  max_packed_thickness_mm integer,
  max_packed_length_mm integer,
  max_packed_width_mm integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT carrier_dispatch_options_method_unique UNIQUE (shipping_method),
  CONSTRAINT carrier_dispatch_options_weight_mode CHECK (
    billing_weight_mode IN ('chargeable', 'actual')
  ),
  CONSTRAINT carrier_dispatch_options_service_type_lower CHECK (
    service_type IS NULL OR service_type = lower(service_type)
  )
);

CREATE TRIGGER carrier_dispatch_options_set_updated_at
  BEFORE UPDATE ON public.carrier_dispatch_options
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

-- ── flat_rate_package_specs ─────────────────────────────────────────────────

CREATE TABLE public.flat_rate_package_specs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_type text NOT NULL,
  size_label text NOT NULL,
  length_mm integer NOT NULL,
  width_mm integer NOT NULL,
  -- Satchels have no fixed depth -- they take whatever fits.
  depth_mm integer,
  -- A flat-rate satchel or box is priced as if it weighed this much, whatever
  -- is actually inside it.
  maps_to_weight_kg numeric(10, 3) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT flat_rate_package_specs_unique UNIQUE (package_type, size_label),
  CONSTRAINT flat_rate_package_specs_type CHECK (package_type IN ('satchel', 'box')),
  CONSTRAINT flat_rate_package_specs_size CHECK (size_label IN ('XS', 'S', 'M', 'L', 'XL'))
);

CREATE TRIGGER flat_rate_package_specs_set_updated_at
  BEFORE UPDATE ON public.flat_rate_package_specs
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

-- ── shipping_settings ───────────────────────────────────────────────────────

-- xpros calls this postage_constants. Renamed to sit alongside
-- pricing_settings, and direct_freight_surcharge is dropped with the carrier
-- (decision 2). Defaults are xpros' production values as of 2026-07-31.
--
-- parcel_volumetric_kg_per_cbm is NOT here: it already lives on
-- pricing_settings, where order_metrics_summary reads it. Moving it would
-- disturb the metrics table for no gain.
CREATE TABLE public.shipping_settings (
  id smallint PRIMARY KEY DEFAULT 1,
  au_post_max_length_mm numeric(10, 2) NOT NULL DEFAULT 1040,
  au_post_max_weight_kg numeric(10, 3) NOT NULL DEFAULT 22,
  eparcel_oversize_surcharge_aud numeric(10, 2) NOT NULL DEFAULT 9.50,
  eparcel_oversize_threshold_mm integer NOT NULL DEFAULT 1000,
  eparcel_fuel_charge_rate numeric(6, 4) NOT NULL DEFAULT 0.0990,
  -- xpros hard-codes this as TIEBREAK_THRESHOLD = 0.05. Config rather than
  -- constant for the same reason order_metrics_summary reads gst_rate from
  -- pricing_settings instead of hard-coding 1.1: it is a business number, and
  -- business numbers change without a deploy.
  quote_tiebreak_threshold numeric(5, 4) NOT NULL DEFAULT 0.05,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT shipping_settings_single_row CHECK (id = 1)
);

CREATE TRIGGER shipping_settings_set_updated_at
  BEFORE UPDATE ON public.shipping_settings
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

INSERT INTO public.shipping_settings (id) VALUES (1);

-- ── RLS ─────────────────────────────────────────────────────────────────────
--
-- Read-only for authenticated across the board. None of these has a CRUD page;
-- they change through migrations. The quote engine runs in Trigger.dev under
-- the service role and bypasses RLS, so nothing here needs write access to do
-- its job.

ALTER TABLE public.carriers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carrier_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carrier_zone_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carrier_dispatch_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flat_rate_package_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_read" ON public.carriers
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON public.carrier_services
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON public.carrier_zone_rates
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON public.carrier_dispatch_options
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON public.flat_rate_package_specs
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "authenticated_read" ON public.shipping_settings
  FOR SELECT TO authenticated USING (true);

GRANT SELECT ON public.carriers TO authenticated;
GRANT SELECT ON public.carrier_services TO authenticated;
GRANT SELECT ON public.carrier_zone_rates TO authenticated;
GRANT SELECT ON public.carrier_dispatch_options TO authenticated;
GRANT SELECT ON public.flat_rate_package_specs TO authenticated;
GRANT SELECT ON public.shipping_settings TO authenticated;

COMMIT;
