BEGIN;

-- Result table for the shipping quote engine. See docs/shipping-quote-engine.md
-- section 2.7.
--
-- One row per carrier option considered, not per order: a single Re-Quote run
-- writes every option it priced, including the ones that failed, so the panel
-- can show why an option is missing rather than just omitting it. Rows from one
-- run share a quoted_at, which is how the UI isolates the latest batch.

CREATE TABLE public.order_shipping_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders (id) ON DELETE CASCADE,
  -- RESTRICT, not CASCADE: deleting a carrier must not quietly erase the
  -- history of what we quoted and charged before it left.
  carrier_id bigint NOT NULL REFERENCES public.carriers (id) ON DELETE RESTRICT,
  shipping_method public.shipping_method NOT NULL,
  service_id bigint REFERENCES public.carrier_services (id) ON DELETE SET NULL,
  zone text,
  quoted_rate numeric(10, 2) NOT NULL DEFAULT 0,
  computation_type text NOT NULL,
  is_selected boolean NOT NULL DEFAULT false,
  -- Set when this option could not be priced. quoted_rate stays 0 and the row
  -- is excluded from selection.
  error_message text,
  quoted_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT order_shipping_quotes_computation_type CHECK (
    computation_type IN ('rate_card', 'api')
  )
);

CREATE INDEX order_shipping_quotes_order_batch_idx
  ON public.order_shipping_quotes (order_id, quoted_at DESC);

-- At most one selected quote per order. xpros leaves this to application code,
-- which means a re-quote that half-fails can leave two rows selected and the
-- order detail page showing whichever sorts first. A partial unique index
-- settles it in the one place that cannot be bypassed.
CREATE UNIQUE INDEX order_shipping_quotes_one_selected_idx
  ON public.order_shipping_quotes (order_id)
  WHERE is_selected;

COMMENT ON TABLE public.order_shipping_quotes IS
  'One row per carrier option priced by a Re-Quote Shipping run; rows sharing quoted_at form one batch.';

ALTER TABLE public.order_shipping_quotes ENABLE ROW LEVEL SECURITY;

-- Written by the Trigger.dev task under the service role, which bypasses RLS.
-- The UI only reads.
CREATE POLICY "authenticated_read" ON public.order_shipping_quotes
  FOR SELECT
  TO authenticated
  USING (true);

GRANT SELECT ON public.order_shipping_quotes TO authenticated;

COMMIT;
