BEGIN;

-- Inventory domain: where stock physically sits and how much of it there is.
-- See docs/inventory-migration.md for the survey of the legacy data and the
-- decisions this implements.
--
-- Source tables: public.go2_locations -> public.locations,
--                public.go2_locations_products -> public.inventory_levels.
-- public.go2_warehouses is deliberately NOT migrated: there is exactly one
-- warehouse, so the level carries no information today. Adding a second one
-- later means introducing a warehouses table, backfilling locations.warehouse_id
-- and moving the name uniqueness below from global to per-warehouse.

-- Storage locations within the (single, implicit) warehouse, e.g. "S-1-1", "P-1-10".
CREATE TABLE public.locations (
  -- Legacy go2_locations.id is reused verbatim, which is what makes the data
  -- migration script idempotent (see scripts/migration/003_inventory_data.sql).
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nullable in the legacy table but populated on all 24 rows; NOT NULL here
  -- because a location nobody can name is not addressable by warehouse staff.
  name text NOT NULL,
  comments text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT locations_name_not_blank CHECK (btrim(name) <> ''),
  -- Global uniqueness is the right scope while there is one warehouse. It has
  -- to become UNIQUE (warehouse_id, name) if a second warehouse is ever added.
  CONSTRAINT locations_name_unique UNIQUE (name)
);

-- How much of a product sits in a given location.
CREATE TABLE public.inventory_levels (
  -- Legacy go2_locations_products.id, reused verbatim (same reason as above).
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Deleting a product removes its stock rows with it; they mean nothing alone.
  product_id bigint NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
  -- RESTRICT so a location that still holds products cannot be deleted out from
  -- under them -- the caller gets a foreign-key error to surface.
  location_id bigint NOT NULL REFERENCES public.locations (id) ON DELETE RESTRICT,
  qty integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  -- The legacy table had 488 negative rows (down to -8390) because Laravel
  -- deducted on sale without ever recording receipts. Those are zeroed on the
  -- way in; this constraint stops the new system from drifting the same way.
  CONSTRAINT inventory_levels_qty_non_negative CHECK (qty >= 0),
  -- One row per product per location; moving stock is an UPDATE, not a second row.
  -- Note this permits one product across several locations even though the
  -- legacy data happens to have exactly one location per product -- readers must
  -- SUM(qty) GROUP BY product_id rather than expect a single row.
  CONSTRAINT inventory_levels_unique_product_location UNIQUE (product_id, location_id)
);

-- Reverse lookup ("what is stored in this location"). product_id needs no index
-- of its own: it is the leading column of the UNIQUE constraint.
CREATE INDEX inventory_levels_location_id_idx
  ON public.inventory_levels (location_id);

-- Same timestamp handling as public.products (migration 20260719150000): the DB
-- owns created_at/updated_at, application code never sets them.
CREATE TRIGGER locations_set_updated_at
  BEFORE UPDATE ON public.locations
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

CREATE TRIGGER inventory_levels_set_updated_at
  BEFORE UPDATE ON public.inventory_levels
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_levels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.locations
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "authenticated_full_access" ON public.inventory_levels
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.locations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.inventory_levels TO authenticated;

COMMIT;
