BEGIN;

-- Customers, deduplicated from the legacy go2_buyers table.
-- See docs/orders-domain-migration.md section 4.2 for the survey behind this.
--
-- go2_buyers is not a customer master: Laravel inserted a fresh row every time it
-- imported an order, so 185241 of its 196085 rows serve exactly one order.
-- Grouping by eBay username (falling back to email) collapses that to 178024
-- real customers, which is what makes "show me this customer's order history"
-- possible at all.
--
-- Addresses deliberately do NOT live here. The same customer ships to different
-- addresses over time (5008 usernames in the legacy data do exactly that), so an
-- address on the customer record would silently rewrite where past orders went.
-- Every order carries its own ship_to_* snapshot instead (see orders).

CREATE TABLE public.customers (
  -- GENERATED BY DEFAULT, like the other migrated tables: the data migration
  -- assigns ids explicitly. It uses the smallest go2_buyers.id in each dedup
  -- group, which is what makes scripts/migration/004_orders_data.sql idempotent
  -- -- a later Laravel backup only ever appends higher ids, so the minimum of a
  -- group never moves and a re-run cannot fork one customer into two.
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- eBay username. Absent on 20347 legacy rows (those group by email instead),
  -- hence nullable; unique when present because it is the platform's own key.
  platform_user_id text,
  full_name text,
  email text,
  phone text,
  -- 89287 legacy emails are @members.ebay.com relay addresses: syntactically
  -- valid, undeliverable once eBay expires them. Flagged explicitly so a future
  -- mailout can exclude them, rather than leaving every caller to re-derive the
  -- rule from a LIKE pattern.
  is_anonymised_email boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT customers_platform_user_id_unique UNIQUE (platform_user_id)
);

-- Lookup by email is case-insensitive, so the index has to be too.
CREATE INDEX customers_email_idx ON public.customers (lower(email));

-- Backs "find the customer by name" in the order screens.
CREATE INDEX customers_full_name_idx ON public.customers (full_name);

-- Same timestamp handling as the rest of the schema (migration 20260719150000):
-- the DB owns created_at/updated_at, application code never sets them.
CREATE TRIGGER customers_set_updated_at
  BEFORE UPDATE ON public.customers
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.customers
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.customers TO authenticated;

COMMIT;
