BEGIN;

-- What the marketplace sold: one row per eBay/Shopify transaction line.
-- See docs/orders-domain-migration.md section 2.3 for why this level exists
-- separately from order_items.
--
-- Short version: this table records the LISTING that was sold (title, listing
-- id, price, postage), while order_items records the internal SKUs that were
-- actually picked to fulfil it. A kit sold as one line here becomes several rows
-- there. Flattening the two together would lose one or the other.

CREATE TABLE public.order_transactions (
  -- Legacy go2_transactions.id reused verbatim (idempotency, as elsewhere).
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- CASCADE: a transaction line means nothing without its order.
  order_id bigint NOT NULL REFERENCES public.orders (id) ON DELETE CASCADE,
  item_title text,
  -- eBay listing id (933 distinct values across 250413 legacy rows).
  item_number text,
  -- The seller-assigned SKU on the listing. This is the input the order_items
  -- trigger resolves against products.sku -- 96.8% of legacy rows match one.
  custom_label text,
  quantity integer NOT NULL,
  -- No CHECK (sale_price >= 0): the legacy data goes down to -640.00 because
  -- refunds and reversals are recorded as negative lines. A non-negative
  -- constraint would abort the migration on real business records.
  sale_price numeric(12, 2) NOT NULL DEFAULT 0,
  postage_and_handling numeric(12, 2) NOT NULL DEFAULT 0,
  sale_date timestamptz NOT NULL,
  paid_on_date timestamptz NOT NULL,
  -- The carrier service the platform reported, which is a different thing from
  -- orders.shipping_method (what the warehouse actually used).
  postage_service text,
  -- Deliberately NOT unique: 23019 values repeat in the legacy data.
  sales_record_number text,
  order_id_ebay text,
  -- Also NOT unique: 77 values repeat.
  transaction_id_ebay text,
  paypal_transaction_id_number text,
  click_and_collect_reference text,
  notes_to_yourself text,
  private_field text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT order_transactions_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX order_transactions_order_id_idx     ON public.order_transactions (order_id);
CREATE INDEX order_transactions_sale_date_idx    ON public.order_transactions (sale_date DESC);
-- Backs "which listings sold this SKU", and the trigger's own lookups.
CREATE INDEX order_transactions_custom_label_idx ON public.order_transactions (custom_label);

CREATE TRIGGER order_transactions_set_updated_at
  BEFORE UPDATE ON public.order_transactions
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

ALTER TABLE public.order_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.order_transactions
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_transactions TO authenticated;

COMMIT;
