BEGIN;

-- Country name -> ISO code reference data, ported from the xpros database
-- alongside public.postcodes (migration 20260809110000).
--
-- What this table is for: collapsing the country names customers type into a
-- single code, which is what fn_standardize_customer_address() does in
-- migration 20260809130000. public.customers.country currently holds 'AU' on
-- 101644 rows and 'Australia' on 76363 -- the same country under two spellings,
-- which is exactly what this fixes.
--
-- Small on purpose. This is not a world atlas: it holds the countries this
-- business has actually shipped to, and an unrecognised name is left untouched
-- rather than guessed at. Add rows here when a new destination appears.
--
-- xpros's `mendix_id` is not carried across, for the same reason as in
-- postcodes: it keys back to a system this project never ran.

CREATE TABLE public.countries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_name text NOT NULL,
  -- ISO 3166-1 alpha-2, enforced. xpros's copy of this data had drifted off the
  -- standard on two of its seven rows -- Japan was 'JPN' (alpha-3) and South
  -- Korea was 'SKN', which is not a code in any ISO revision. Both are corrected
  -- here, to 'JP' and 'KR'. Neither value had reached go2office (no customer
  -- ships to either country yet), so this is a fix at the source rather than a
  -- data migration -- but importing them verbatim would have planted a
  -- standards violation that only surfaces on the first Japanese order.
  country_code text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT countries_code_format CHECK (country_code ~ '^[A-Z]{2}$'),
  -- The lookup is case-insensitive on the name, so uniqueness has to be too --
  -- otherwise 'Australia' and 'AUSTRALIA' could both sit here and the
  -- standardiser's LIMIT 1 would pick between them arbitrarily.
  CONSTRAINT countries_code_unique UNIQUE (country_code)
);

CREATE UNIQUE INDEX countries_country_name_key ON public.countries (lower(country_name));

CREATE TRIGGER countries_set_updated_at
  BEFORE UPDATE ON public.countries
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.countries
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.countries TO authenticated;

INSERT INTO public.countries (country_name, country_code) VALUES
  ('Australia', 'AU'),
  ('New Zealand', 'NZ'),
  ('United States', 'US'),
  ('Canada', 'CA'),
  ('China', 'CN'),
  ('Japan', 'JP'),
  ('South Korea', 'KR')
ON CONFLICT (country_code) DO NOTHING;

COMMIT;
