BEGIN;

-- Kit composition: which products (and how many of each) make up a kit product.
-- There is no separate "kits" table — a kit is itself a row in public.products
-- (flagged with is_kit), so both columns are foreign keys back to products.
-- See docs/product-kits-migration.md for the migration decisions this implements.
--
-- Source table: public.go2_kits (kit_id -> kit_product_id, product_id -> component_product_id).
CREATE TABLE public.product_kit_items (
  -- Legacy go2_kits.id is reused verbatim, which is what makes the data
  -- migration script idempotent (see scripts/migration/002_product_kits_data.sql).
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The kit. Deleting the kit product removes its composition lines with it.
  kit_product_id bigint NOT NULL REFERENCES public.products (id) ON DELETE CASCADE,
  -- The component. RESTRICT so a product still used inside a kit cannot be
  -- deleted silently — the caller gets a foreign-key error to surface.
  component_product_id bigint NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
  qty integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_kit_items_qty_positive CHECK (qty > 0),
  CONSTRAINT product_kit_items_no_self_reference CHECK (kit_product_id <> component_product_id),
  -- One line per component per kit; changing a quantity is an UPDATE, not a
  -- second row.
  CONSTRAINT product_kit_items_unique_component UNIQUE (kit_product_id, component_product_id)
);

-- Reverse lookup ("which kits contain this product"). kit_product_id needs no
-- index of its own: it is the leading column of the UNIQUE constraint.
CREATE INDEX product_kit_items_component_product_id_idx
  ON public.product_kit_items (component_product_id);

-- Same timestamp handling as public.products (migration 20260719150000): the DB
-- owns created_at/updated_at, application code never sets them.
CREATE TRIGGER product_kit_items_set_updated_at
  BEFORE UPDATE ON public.product_kit_items
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

ALTER TABLE public.product_kit_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.product_kit_items
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_kit_items TO authenticated;

COMMIT;
