BEGIN;

-- Audit trail for automatic changes to an order. See
-- docs/shipping-quote-engine.md section 2.7.
--
-- This exists because the quote engine rewrites orders.status on its own in two
-- cases: a postal-only address the package is too big or heavy for any postal
-- carrier to take, and an order no carrier at all can quote. Both move the
-- order to `issued` for a human to sort out.
--
-- Without a log that is a status change nobody asked for and nobody can trace
-- afterwards -- the same silent-rewrite problem the product-name initcap guard
-- (migration 20260808140000) and the customer address standardiser (20260809130000)
-- are each built to avoid. Here the write is wanted; what was missing is the
-- record of it.
--
-- Deliberately minimal: it holds what happened and who did it, not a diff. The
-- shipping quotes themselves are already in order_shipping_quotes.

CREATE TABLE public.order_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders (id) ON DELETE CASCADE,
  action text NOT NULL,
  -- NULL when the actor is a background task rather than a person -- which is
  -- every row the quote engine writes, since it runs under the service role.
  user_id uuid REFERENCES auth.users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX order_logs_order_id_idx
  ON public.order_logs (order_id, created_at DESC);

COMMENT ON TABLE public.order_logs IS
  'Audit trail for automatic changes to an order, chiefly status rewrites made by the shipping quote engine.';

ALTER TABLE public.order_logs ENABLE ROW LEVEL SECURITY;

-- Written by the Trigger.dev task under the service role, which bypasses RLS.
-- An audit trail the application can edit is not one, so the UI only reads.
CREATE POLICY "authenticated_read" ON public.order_logs
  FOR SELECT
  TO authenticated
  USING (true);

GRANT SELECT ON public.order_logs TO authenticated;

COMMIT;
