BEGIN;

-- Order headers, migrated from go2_orders (+ the address snapshot from
-- go2_buyers). See docs/orders-domain-migration.md sections 2.4 and 4.3.
--
-- Four legacy columns are deliberately NOT carried over:
--   payment_method -- 88100 blanks, mixed casing, and roughly 15 rows where a
--                     shipping charge ("AU $8.95") was typed into it;
--   total_sale     -- 61329 rows are 0 because the 2020 import from the previous
--                     XOFFICE system never brought the totals across. It is
--                     recomputable from order_transactions, so it is now a view
--                     (public.order_totals) rather than a column that lies;
--   is_atl         -- 0 on all 203315 rows;
--   est_profit     -- 0 on all 203315 rows.
-- Also dropped: logs (1.8M lines of audit text, retired by decision) and
-- ebay_user_id (only ever NULL or 2, with no table to join to).

CREATE TABLE public.orders (
  -- Legacy go2_orders.id reused verbatim, which is what makes the data
  -- migration script idempotent (see scripts/migration/004_orders_data.sql).
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- RESTRICT: a customer with orders on file cannot be deleted out from under
  -- them; the caller gets a foreign-key error to surface.
  customer_id bigint NOT NULL REFERENCES public.customers (id) ON DELETE RESTRICT,
  -- Populated and globally unique on all 203315 legacy rows -- the closest thing
  -- to a business key this domain has, and the main search entry point.
  invoice_number text NOT NULL,
  status public.order_status NOT NULL,
  platform public.sales_platform NOT NULL,
  shipping_method public.shipping_method,
  -- Historical values for the seven retired carriers (Zone6, Sendle, Winit,
  -- Fast Track, Toll B2C -- 29143 orders) that have no home in the new enum.
  -- Nothing writes this column going forward; it exists so 14.3% of the order
  -- history does not lose its shipping method. Read it as
  -- COALESCE(shipping_method::text, legacy_shipping_method).
  legacy_shipping_method text,
  transit_cover numeric(12, 2) NOT NULL DEFAULT 0,
  tracking_number text,
  parcel_zone text,
  -- Shopify (and other non-eBay) order number. NULL on the 182551 eBay orders.
  web_order_id text,
  comments text,
  -- When the parcel went out. NULL means not dispatched yet (4919 legacy rows).
  posted_on_date timestamptz,
  -- Delivery address as it stood when the order was placed, snapshotted from the
  -- go2_buyers row. Not a foreign key to an address table and not derived from
  -- customers: where a parcel actually went is a fact about the order, and must
  -- not change when the customer later updates their details.
  --
  -- Migrated verbatim, with no normalisation: the legacy data mixes NSW with
  -- New South Wales and AU with Australia, and cleaning that up is a separate
  -- decision the business has deferred.
  ship_to_name text,
  ship_to_company text,
  ship_to_phone text,
  ship_to_line1 text,
  ship_to_line2 text,
  -- 129276 of these hold an eBay reference code (`ebay:zsqywfc`) rather than an
  -- address line -- only 4899 distinct values across 129k rows, so it is not a
  -- buyer identifier either. Kept as-is by explicit decision.
  ship_to_line3 text,
  ship_to_line4 text,
  ship_to_city text,
  ship_to_state text,
  ship_to_postcode text,
  ship_to_country text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT orders_invoice_number_unique UNIQUE (invoice_number),
  CONSTRAINT orders_transit_cover_non_negative CHECK (transit_cover >= 0)
);

-- At 203315 rows these are not an optimisation. The list screen sorts by date
-- descending and filters by status/platform; without them every page is a seq
-- scan over the whole table.
CREATE INDEX orders_customer_id_idx     ON public.orders (customer_id);
CREATE INDEX orders_status_idx          ON public.orders (status);
CREATE INDEX orders_platform_idx        ON public.orders (platform);
CREATE INDEX orders_posted_on_date_idx  ON public.orders (posted_on_date DESC NULLS LAST);
CREATE INDEX orders_created_at_idx      ON public.orders (created_at DESC);
CREATE INDEX orders_tracking_number_idx ON public.orders (tracking_number);

CREATE TRIGGER orders_set_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.orders
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO authenticated;

COMMIT;
