BEGIN;

-- What the warehouse actually picks: internal SKUs and counts, expanded from the
-- listing sold in order_transactions. See docs/orders-domain-migration.md
-- sections 2.3 and 5.
--
-- Rows here are maintained automatically by the trigger added in migration
-- 20260803150000: whenever a transaction's custom_label or quantity changes, its
-- items are rebuilt by resolving the label to a product and, if that product is
-- a kit, expanding it through product_kit_items.
--
-- The 250687 rows carried over from Laravel are NOT regenerated -- they are the
-- record of what was really shipped, and 3026 of them cannot be reproduced at
-- all because their custom_label matches no SKU. See is_auto_generated below.

CREATE TABLE public.order_items (
  -- Legacy go2_transactions_products.id reused verbatim for migrated rows.
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id bigint NOT NULL
    REFERENCES public.order_transactions (id) ON DELETE CASCADE,
  -- Nullable, ON DELETE SET NULL: deleting a product must never delete the
  -- record of having sold it. 334 migrated rows already arrive NULL here because
  -- they point at 15 products Laravel soft-deleted (public.products excludes
  -- those). The trigger also writes NULL when it cannot resolve custom_label.
  product_id bigint REFERENCES public.products (id) ON DELETE SET NULL,
  -- The SKU text as it stood at the time. This is the only surviving clue when
  -- product_id is NULL, and the thing an operator needs in order to fix such a
  -- row by hand.
  sku_snapshot text,
  quantity integer NOT NULL,
  -- Where the goods were picked from. The legacy column was free text; all 28893
  -- non-null values matched a locations.name exactly, so it becomes a real
  -- foreign key here. SET NULL rather than RESTRICT: retiring a location should
  -- not be blocked by, or destroy, years of order history.
  location_id bigint REFERENCES public.locations (id) ON DELETE SET NULL,
  -- false = migrated from Laravel or edited by a human; true = produced by the
  -- rebuild trigger. Migrated rows are all false, which is also how the
  -- migration verifies the trigger really was disabled while it ran (a stray
  -- true means history got overwritten -- see section 5.6 of the doc).
  is_auto_generated boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT order_items_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX order_items_transaction_id_idx ON public.order_items (transaction_id);
CREATE INDEX order_items_product_id_idx     ON public.order_items (product_id);
CREATE INDEX order_items_location_id_idx    ON public.order_items (location_id);
-- Backs the "unresolved lines needing attention" queue (3066 rows on migration).
CREATE INDEX order_items_unresolved_idx
  ON public.order_items (transaction_id)
  WHERE product_id IS NULL;

CREATE TRIGGER order_items_set_updated_at
  BEFORE UPDATE ON public.order_items
  FOR EACH ROW
  EXECUTE FUNCTION extensions.moddatetime (updated_at);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON public.order_items
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO authenticated;

COMMIT;
